# Load necessary libraries
library(dplyr)
library(ggplot2)
library(corrplot)
library(tidyr)
library(gridExtra)
library(patchwork)
library(treemap)

# Load the datasets (mean imputation)  
co2_data <- read.csv("Data/Imputed Data/Co2(Mean Imp).csv", stringsAsFactors = FALSE)
energy_data <- read.csv("Data/Imputed Data/Energy(Mean Imp).csv", stringsAsFactors = FALSE)

# View the structure of both datasets (OPTIONAL)
str(co2_data)
str(energy_data)

# Preview the first few rows of both datasets (OPTIONAL)
head(co2_data)
head(energy_data)

# Check for missing values in both datasets (OPTIONAL)
colSums(is.na(co2_data))
colSums(is.na(energy_data))

# Summary statistics for CO2 Emissions and Energy Generation (OPTIONAL)
summary(co2_data)
summary(energy_data)

# Change the column names
Column <- c("Total Emissions", "Coal and Coke", "Natural Gas", "Petroleum")
names(co2_data)[3:6] <- Column
ColumnE <- c("Nuclear", "Total Renewables", "Hydroelectricity", "Non-Hydroelectricity", "Geothermal", 
             "Wind", "Biowaste", "Solar")
names(energy_data)[3:10] <- ColumnE


#### DATA VISUALIZATION ####
# Line Bar plot for Total CO2 Emissions over time
TS <- ggplot(co2_data, aes(x = Year, y = `Total Emissions`)) +
  geom_bar(stat = "identity") +
  labs(title = "Total CO2 Emissions Over Time", x = "Year", y = "Total CO2 Emissions (MM tonnes)") +
  theme_minimal()

# Stacked bar plot for CO2 Emissions by source for each Country
co2_data <- co2_data %>%
  gather(Source, Emissions, `Coal and Coke`:Petroleum)

TS2 <- ggplot(co2_data, aes(x = Year, y = Emissions, fill = Source)) +
  geom_bar(stat = "identity") +
  labs(title = "CO2 Emissions by Source Over Time", x = "Country", y = "CO2 Emissions (MM tonnes)") +
  theme_minimal()

# Line bar plot for Total Renewable Energy over time grouped by Country
TS3 <- ggplot(energy_data, aes(x = Year, y = `Total Renewables`)) +
  geom_bar(stat = "identity") +
  labs(title = "Total Renewable Energy Generation Over Time", x = "Year", y = "Total Renewables (quad Btu)") +
  theme_minimal()

# Stacked bar plot for CO2 Emissions by source for each Country
energy_data <- energy_data %>%
  gather(Source, Generated, Hydroelectricity, Geothermal:Solar)

TS4 <- ggplot(energy_data, aes(x = Year, y = Generated, fill = Source)) +
  geom_bar(stat = "identity") +
  labs(title = "Energy Generated by Renewable Energy Sources Over Time", x = "Country", y = "Electricity Generated (quad btu)") +
  theme_minimal()

# Arrange plots in a grid
grid.arrange(TS, TS2, TS3, TS4, ncol = 2)  # 2 columns



# read the csv file and get all the data in a specific country (Change "World" to try another country)
electricity_generated <- read.csv("Data/Merge Data/Electricity Generation(cleansed).csv")
co2_emissions <- read.csv("Data/Merge Data/CO2 Emissions(cleansed).csv")


# Change the column names (see Line 30 and 32)
names(co2_emissions)[3:6] <- Column
names(electricity_generated)[3:10] <- ColumnE


# Filter for a specific country (e.g., USA)
world_data_Co2 <- co2_emissions %>% filter(Country == "World")
world_data_Elec <- electricity_generated %>% filter(Country == "World")
# Filter for a specific year (e.g., 2020)
energy_2020 <- energy_data %>% filter(Year == 2020)
co2_2020 <- co2_data %>% filter(Year == 2020)


# Reshape data to long format for pie chart
world_data_Co2 <- world_data_Co2 %>%
  gather(Source, Emissions, `Coal and Coke`:Petroleum)
world_data_Elec <- world_data_Elec %>%
  gather(Source, Generated, Hydroelectricity, Geothermal:Solar)


# Pie chart for CO2 Emissions by source
PC1 <- ggplot(world_data_Co2, aes(x = "" , y = Emissions, fill = Source)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  labs(title = "Total CO2 Emissions", x = "", y = "Emissions (MM tonnes)") +
  theme_void()

# Pie chart for electricity Generation by source
PC2 <- ggplot(world_data_Elec, aes(x = "" , y = Generated, fill = Source)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  labs(title = "Total Energy Generation", x = "", y = "Energy Generation(quad btu)") +
  theme_void()

# Pie chart for renewable energy sources in 2020
PC3 <- ggplot(energy_2020, aes(x = "", y = Generated, fill = Source)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  labs(title = "Renewable Energy Sources in 2020", x = "", y = "Energy Generated (quad Btu)") +
  theme_void()

PC4 <- ggplot(co2_2020, aes(x = "", y = Emissions, fill = Source)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y") +
  labs(title = "Carbon Emission Sources in 2020", x = "", y = "Carbon Emissions()") +
  theme_void()

# Arrange plots in a grid
grid.arrange(PC1, PC2, PC3, PC4, ncol = 2)  # 2 columns

# Summarize total renewable energy generation per country
energy_summary <- energy_data %>%
  group_by(Country) %>%
  summarise(Total_Renewable = sum(`Total Renewables`, na.rm = TRUE))

# Create a treemap
treemap(energy_summary,
        index = "Country",
        vSize = "Total_Renewable",
        title = "Total Renewable Energy Generation by Country",
        palette = "Greens")



#STOP HERE#
ggplot(energy_data, aes(x = Year, y = Generated, fill = Source)) +
  geom_area() +
  labs(title = "Renewable Energy Generation Over Time by Source", x = "Year", y = "Energy Generated (quad Btu)") +
  theme_minimal()

##### FIX THIS #####
# Box plot of CO2 Emissions from Coal in different years
ggplot(co2_emissions, aes(x = Year, y = CO2.Emissions..Coal.Coke....MMtonnes, group = Country)) +
  geom_boxplot() +
  labs(title = "CO2 Emissions from Coal in different years", x = "Year", y = "CO2 Emissions from Coal (MM tonnes)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

## Dapat may world map(maybe add details about longitude and latitude)
# Heatmap of CO2 emissions by source and Year
ggplot(co2_emissions_long, aes(x = Year, y = Country, fill = Emissions)) +
  geom_tile() +
  labs(title = "Heatmap of CO2 Emissions by Source and Country", x = "Country", y = "Emission Source") +
  scale_fill_gradient(low = "lightblue", high = "red") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Stacked area plot of renewable energy generation over time
ggplot(energy_long, aes(x = Year, y = Generation, fill = Renewable_Source)) +
  geom_area() +
  labs(title = "Renewable Energy Generation Over Time by Source", x = "Year", y = "Energy Generated (quad Btu)") +
  theme_minimal()


